console.log("Primeira Linha \n Segunda linha")
console.log("Weverton com 'aspas' duplas.")
console.log('Weverton com "aspas" simples.' + ' Daniel com aspas simples')
console.log(`Weverton com crase.`)
console.log(5 + 2 * 2) 

console.log(typeof "Weverton com aspas duplas.")
console.log(typeof 'Weverton com aspas simples.')
console.log(typeof `Weverton com crase.`)
console.log(typeof 5 + 2 * 2) 
